using Logic.ReflectionMetadata;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using System.Linq;

namespace UnitTest.ReflectionMetadata.Metadata
{
    [TestClass()]
    public class MethodMetadataTests
    {
        IEnumerable<MethodMetadata> methods;

        [TestInitialize]
        public void Init()
        {
            methods = TestAssemblyBuilder.GetMethodmetadatas();


        }

        [TestMethod()]
        public void NamesTest()
        {
            Assert.IsNotNull(methods);
            List<string> expectedNames = new List<string> {     "get_Linq2SQL",
                                                                "set_Linq2SQL",
                                                                "ToString",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "GetType",
                                                                "get_ServiceB",
                                                                "set_ServiceB",
                                                                "ToString",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "GetType",
                                                                "get_ServiceC",
                                                                "set_ServiceC",
                                                                "ToString",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "GetType",
                                                                "get_ServiceA",
                                                                "set_ServiceA",
                                                                "ToString",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "GetType",
                                                                "get_Model",
                                                                "set_Model",
                                                                "ToString",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "GetType",
                                                                "get_Property1",
                                                                "set_Property1",
                                                                "AbstractMethod",
                                                                "ToString",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "GetType",
                                                                "ToString",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "GetType",
                                                                "AbstractMethod",
                                                                "get_Property1",
                                                                "set_Property1",
                                                                "ToString",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "GetType",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "ToString",
                                                                "ToString",
                                                                "CompareTo",
                                                                "ToString",
                                                                "ToString",
                                                                "HasFlag",
                                                                "GetTypeCode",
                                                                "GetType",
                                                                "get_GenericProperty",
                                                                "set_GenericProperty",
                                                                "GenericMethod",
                                                                "ToString",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "GetType",
                                                                "MethodA",
                                                                "MethodB",
                                                                "MethodA",
                                                                "MethodB",
                                                                "ToString",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "GetType",
                                                                "Connect",
                                                                "ToString",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "GetType",
                                                                "ToString",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "GetType",
                                                                "get_StaticProperty",
                                                                "set_StaticProperty",
                                                                "StaticMethod1",
                                                                "StaticMethod2",
                                                                "ToString",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "GetType",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "ToString",
                                                                "GetType",
                                                                "get_ClassB",
                                                                "set_ClassB",
                                                                "ToString",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "GetType",
                                                                "get_ClassA",
                                                                "set_ClassA",
                                                                "ToString",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "GetType",
                                                                "ToString",
                                                                "Equals",
                                                                "GetHashCode",
                                                                "GetType"
            };
            IEnumerable<string> TypeNames = from MethodMetadata _method in methods
                                            select _method.Name;

            CollectionAssert.AreEquivalent(expectedNames, TypeNames.ToList());
        }

        [TestMethod()]
        public void ReturnTypeNamesTest()
        {
            List<string> expectedNames = new List<string> {"Linq2SQL",
                                                            "Void",
                                                            "String",
                                                            "Boolean",
                                                            "Int32",
                                                            "Type",
                                                            "ServiceB",
                                                            "Void",
                                                            "String",
                                                            "Boolean",
                                                            "Int32",
                                                            "Type",
                                                            "ServiceC",
                                                            "Void",
                                                            "String",
                                                            "Boolean",
                                                            "Int32",
                                                            "Type",
                                                            "ServiceA",
                                                            "Void",
                                                            "String",
                                                            "Boolean",
                                                            "Int32",
                                                            "Type",
                                                            "Model",
                                                            "Void",
                                                            "String",
                                                            "Boolean",
                                                            "Int32",
                                                            "Type",
                                                            "String",
                                                            "Void",
                                                            "Void",
                                                            "String",
                                                            "Boolean",
                                                            "Int32",
                                                            "Type",
                                                            "String",
                                                            "Boolean",
                                                            "Int32",
                                                            "Type",
                                                            "Void",
                                                            "String",
                                                            "Void",
                                                            "String",
                                                            "Boolean",
                                                            "Int32",
                                                            "Type",
                                                            "Boolean",
                                                            "Int32",
                                                            "String",
                                                            "String",
                                                            "Int32",
                                                            "String",
                                                            "String",
                                                            "Boolean",
                                                            "TypeCode",
                                                            "Type",
                                                            "T",
                                                            "Void",
                                                            "T",
                                                            "String",
                                                            "Boolean",
                                                            "Int32",
                                                            "Type",
                                                            "Void",
                                                            "Single",
                                                            "Void",
                                                            "Single",
                                                            "String",
                                                            "Boolean",
                                                            "Int32",
                                                            "Type",
                                                            "Void",
                                                            "String",
                                                            "Boolean",
                                                            "Int32",
                                                            "Type",
                                                            "String",
                                                            "Boolean",
                                                            "Int32",
                                                            "Type",
                                                            "Int32",
                                                            "Void",
                                                            "Void",
                                                            "Single",
                                                            "String",
                                                            "Boolean",
                                                            "Int32",
                                                            "Type",
                                                            "Boolean",
                                                            "Int32",
                                                            "String",
                                                            "Type",
                                                            "ClassB",
                                                            "Void",
                                                            "String",
                                                            "Boolean",
                                                            "Int32",
                                                            "Type",
                                                            "ClassA",
                                                            "Void",
                                                            "String",
                                                            "Boolean",
                                                            "Int32",
                                                            "Type",
                                                            "String",
                                                            "Boolean",
                                                            "Int32",
                                                            "Type"
            };
            IEnumerable<string> ReturnTypeNames = from MethodMetadata _method in methods
                                                  select _method.ReturnType.TypeName;

            CollectionAssert.AreEquivalent(expectedNames, ReturnTypeNames.ToList());
        }


    }
}